--- django/contrib/gis/gdal/libgdal.py	2016-08-01 15:12:34.000000000 -0300
+++ django/contrib/gis/gdal/libgdal.py	2016-08-03 07:42:31.341152913 -0300
@@ -2,6 +2,7 @@
 
 import logging
 import os
+import sys
 import re
 from ctypes import CDLL, CFUNCTYPE, c_char_p, c_int
 from ctypes.util import find_library
@@ -11,13 +12,12 @@
 
 logger = logging.getLogger('django.contrib.gis')
 
-# Custom library path set?
-try:
-    from django.conf import settings
-    lib_path = settings.GDAL_LIBRARY_PATH
-except (AttributeError, EnvironmentError,
-        ImportError, ImproperlyConfigured):
-    lib_path = None
+if 'linux' in sys.platform:
+    lib_path = os.path.join(sys.prefix, 'lib', 'libgdal.so')
+elif 'darwin' in sys.platform:
+    lib_path = os.path.join(sys.prefix, 'lib', 'libgdal.1.dylib')
+elif os.name == 'nt':
+    lib_path = os.path.join(sys.prefix, 'Library', 'bin', 'gdal111.dll')
 
 if lib_path:
     lib_names = None
